### ISSUE TITLE
Generate the matched-filtering templates using the PyCBC software

### ISSUE THREAD

**Issue by chrismessenger** [hagabbar/matching_cnn_paper#24]
We need a 3% mismatch bank of templates on the mass space placed as one would do for a real GW search (without spins).

We need to make sure that the noise curve (which determines the density) is the same as used in our data generation.

**Comment by hagabbar** [comment]
Will do. I think this should probably be implemented in the gen_bbh function, correct?

**Comment by chrismessenger** [comment]
So, this shouldn't be in the gen_bbh function that we use to make the training, validation, and test datasets.

This should only be used in the code used to compute the matched-filtering results. Is there a copy of the gen_bbh function in those scripts? I've never looked at the matched-filtering scripts.

**Comment by hagabbar** [comment]
Apologies, I meant the gen_bbh function the mf_1det.py scripts (matched-template filtering script). Michael must have copied the functions you used.

**Comment by hagabbar** [comment]
This might sound like a naive question, but should the mismatch only be in terms of the template bank component mass space?

**Comment by chrismessenger** [comment]
Your question might need a bit of clarification but I the answer is yes (I think).

You want to know how far away from each other to place a set of location in m1-m2 space such that a true signal exactly midway between them in mass would incur a loss in overall SNR of only 3% when either of them is used to recover the signal.

It should have nothing to do with any other parameters.  However, the overall density scale of the template bank is governed by the lower frequency cut-off and the PSD. We will have to talk about the details tomorrow.

**Comment by hagabbar** [comment]
Ah okay. I'll continue looking at the current iteration of the matched template filtering code and try to understand as much as I can before we meet.

**Comment by hagabbar** [comment]
This issue has been resolved. Can I close?
