### ISSUE TITLE
ROC curve plots

### ISSUE THREAD

**Issue by chrismessenger** [hagabbar/matching_cnn_paper#30]
We need to decide on a better way to show the ROC results. We certainly don't need to show plots for SNR 10 and 12.

It would be good to have the same axis ranges on all plots but may not be practical.

One possibility is to have 1 plot with many curves but that could get very messy.

**Comment by mj-will** [comment]
Shall try a version with all the curves and post a link here when ready.

**Comment by mj-will** [comment]
Here's a plot without SNR 10 and 12 (plus same axis ranges) and a single plot with SNRs 2-8:
![roc_curves_single](https://user-images.githubusercontent.com/25609742/32133117-5e4327b4-bbc9-11e7-9a97-d61d6db02683.png)
![roc_curves](https://user-images.githubusercontent.com/25609742/32133121-64728792-bbc9-11e7-896a-f4663af15a12.png)
Thoughts?

**Comment by chrismessenger** [comment]
I like the single plot but you could drop the snr 8 results.

Cheers

Chris

Sent from my iPhone

On 28 Oct 2017, at 10:20, Michael Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's a plot without SNR 10 and 12 (plus same axis ranges) and a single plot with SNRs 2-8:
[roc_curves_single]<https://user-images.githubusercontent.com/25609742/32133117-5e4327b4-bbc9-11e7-9a97-d61d6db02683.png>
[roc_curves]<https://user-images.githubusercontent.com/25609742/32133121-64728792-bbc9-11e7-896a-f4663af15a12.png>
Thoughts?

**Comment by mj-will** [comment]
Removed SNR 8 and uploaded the plot to the repository (also fixed the SN typo).
I'm also looking into adding the errors using the binomial distribution.

**Comment by mj-will** [comment]
Seeing as the ROC curves have been brought up in Tom's comments, I think updates to the plots should be discussed there.
