### ISSUE TITLE
Marco: is the cyan curve whitened in figure 1?

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#41]
The caption of figure 1 reads: " A whitened noise-free time series of a BBH signal (cyan) with component masses..." Is the cyan curve really whitened?

**Comment by mj-will** [comment]
I've checked the code and the signal (cyan curve) is whitened before plotting. But I'll do some further checks to be sure.

**Comment by mj-will** [comment]
Replotted the waveform with the modified whitening function Chris sent. Will upload a .pdf version to the repository when we're clear on the issues with the windowing.

![waveform](https://user-images.githubusercontent.com/25609742/32836389-86337828-ca01-11e7-8f68-decfbaa71c11.png)

**Comment by mj-will** [comment]
Uploaded the updated pdf version and Chris verified that waveform is correctly whitened.
