### ISSUE TITLE
Tom: Fermi, integral papers

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#44]
Not sure why you are citing the Fermi and Integral papers and the MMA paper here in the introduction - which are not relevant to detection of CBC signals in GW data - when you don't include citations to the basic CBC matched filter literature or to recent work on template banks.

**Comment by hagabbar** [comment]
I think Tom just wrote after having only read the first paragraph of the intro. Later on in the section we cite more literature directly related to what he is requesting. I propose to close this issue.
