### ISSUE TITLE
Tom: Seperate template bank and waveform references

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#45]
In the next paragraph it's hard to give a proper set of citations unless you separate the idea of the bank from the idea of the waveforms. The citation [12-19] on line 51 seems to mix the two together. Assuming that we're talking about the bank construction, your citations run out in 2009. However the banks used in O1 and O2 use more recent methods. Should cite arXiv:1705.01845, arXiv:1405.6731, arXiv:1310.5633, arXiv:1210.6666, arXiv:1207.6406. Optionally remove the current refs [13-16] as obsolete (they consider inaccurate or incomplete waveform models).

**Comment by hagabbar** [comment]
This issue has been resolved.
