### ISSUE TITLE
Tom: Citation needed on formulae used

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#47]
'density of templates one would use in m.f.' - These formulae may be correct for a bank that's appropriate for some inspiral PN waveform, I haven't checked. Should cite where you got the formulae from (Owen-Sathya?). You should also mention that the correct density of templates for the actual inspiral-merger-ringdown waveforms is expected to be (somewhat) different. 

BTW on the last point, can cite https://arxiv.org/abs/1501.04418 which discusses the appropriate metric for a previous version of the IMRPhenom waveform.

**Comment by hagabbar** [comment]
@chrismessenger Do you know where we get these equations from?

**Comment by hagabbar** [comment]
Can we just say in the paper we derived this from Babak et al and then quote the paper?

**Comment by hagabbar** [comment]
Added suggested citation and said that we derived our mass distribution from Babak et al.
