### ISSUE TITLE
Tom: Cite PyCBC and mention which tools are used

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#50]
'using the PyCBC tools' : this is not specific. Which code was used? Was it a geometric non-spinning bank? or stochastic? What value of f_lower was given to generate the bank (number of templates depends strongly on this)? In any case it would be more appropriate to give a software citation here, eg

    @misc{pycbc-software,
      author       = {Alex Nitz and others},
      title        = {PyCBC software},
      month        = sep,
      year         = 2017,
      version      = {1.7.11},
      publisher    = {Zenodo},
      doi          = {10.5281/zenodo.883086},
      url          = {https://ligo-cbc.github.io/}
    }

adjusted for whatever version you actually used.

**Comment by hagabbar** [comment]
This issue has also been resolved.
