### ISSUE TITLE
Tom: More detail in matched filtering modified for Gaussian noise

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#53]
l 400 onwards: it's not very clear what 'changes to the ranking statistic' means and there are no citations. I suspect you mean signal consistency statistics such as chisq (cite Allen gr-qc/0405045) and then one could also cite recent papers which combine chisq with other quantities to obtain a ranking statistic, eg arXiv:1705.01513.

**Comment by hagabbar** [comment]
Perhaps make reference to Bruce Allen and combine. Does this satisfy Tom's comment?

**Comment by hagabbar** [comment]
Suggested references have been added.
