### ISSUE TITLE
Tom: Irrelevant reference?

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#55]
One more minor point, ref.[36] is cited for low-latency searches via NN being several orders of magnitude faster than other methods (l.75) however this paper seems to describe an image classifier which is used to validate bank documents. I'm not sure what the connection is.

**Comment by hagabbar** [comment]
@chrismessenger @Fergus-Hayes @mj-will I went ahead and just removed this reference.
