### ISSUE TITLE
Marco: Suggested reference to add from the dcc

### ISSUE THREAD

**Issue by Fergus-Hayes** [hagabbar/matching_cnn_paper#59]
With references 33 and 34, I would suggest to add also https://dcc.ligo.org/LIGO-P1700254 (also on the arxiv) as it deals with CNN applied to glitch investigations.

That will be line 71 of our latest draft.

**Comment by hagabbar** [comment]
Ah thanks for pointing this out to me Fergus!

**Comment by hagabbar** [comment]
@Fergus-Hayes I've been looking around for this paper on the arxiv, but I can't seem to find it anywhere. Have you had any luck?

**Comment by Fergus-Hayes** [comment]
This is the trouble I had. I can only locate it on the dcc from the link, but then I cannot find it on arxiv, and it does not appear anywhere else I look.

**Comment by hagabbar** [comment]
I emailed Marco and he wasn't able to find it either. Since neither I, nor Fergus or Marco have been able to find the paper anywhere other than the DCC, I'll go ahead and leave this out of the paper.
